name: API Deploy

on:
  push:
    paths-ignore:
      - '.github/workflows/server-deploy.yml'
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.18'

      - name: go tests
        run: go test -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=3m

  build:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: docker login ghcr.io -u heartwilltell -p ${{ github.token }}

      - name: Docker build
        run: |
          docker build \
          --build-arg VERSION=${{ github.sha }} \
          --build-arg BRANCH=${{ github.ref }} \
          --build-arg COMMIT=${{ github.sha }} \
          -t ghcr.io/heartwilltell/ladiesquotes-api:${{ github.sha }} \
          -t ghcr.io/heartwilltell/ladiesquotes-api:latest \
          .

      - name: Docker push
        run: |
          docker push ghcr.io/heartwilltell/ladiesquotes-api:${{ github.sha }}
          docker push ghcr.io/heartwilltell/ladiesquotes-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: deploy
        env:
          SECRET_KEY: ${{ secrets.SSH_KEY }}
        run: |
          doctl kubernetes cluster kubeconfig save theplace
          helm upgrade --install -n ladiesquotes -f ./.helm/api/values.yaml --set image.tag=${{ github.sha }} --set app.spacesKey=${{ secrets.DO_SPACES_KEY }} --set app.spacesSecret=${{ secrets.DO_SPACES_SECRET }} --set app.authSecret=${{ secrets.AUTH_SECRET }} --set imagePullSecret.secret=${{ secrets.GHCR }} api ./.helm/api