name: Merge to Main

on:
  push:
    paths-ignore:
      - internal/houston/ui
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - name: go tests
        run: go test -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.23'

      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=3m